### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by song9446** [song9446/lottery-optimizer#1]
다음과 같이 만들것임:
https://ovenapp.io/view/4QhId62Ppj4Omtf6vJtiyFFi11adgqw0/lvdMJ

아래 ToDo리스트에서 하고싶은거 할당 받아가고 코멘트로 업데이트하고

다했으면 체크표시후 코멘트로 또 업데이트 ㄱㄱ

할당됨
- [x] 최적화 번호생성기 로직 구현 - 점진
- [x] 메인페이지 UI - 점진
- [x] 당첨확률 계산로직 구현 - 점진
- [x] 안내 페이지 UI - 점진
- [x] 즐겨찾기 페이지 UI - 큐슈
- [x] 즐겨찾기 페이지 당첨여부 확인 기능 구현- 큐슈
- [x] 에드몹 광고 넣기 - 점진

미할당됨
- [x] 즐겨찾기 페이지 합치기

**Comment by rnpfrenfg** [comment]
즐겨찾기 페이지 UI
 즐겨찾기 페이지 당첨여부 확인 기능 구현

**Comment by song9446** [comment]
메인페이지 완성됐고 브랜치 따로 파놨음. 즐겨찾기 페이지 완성되면 내가 합치겠음.

**Comment by song9446** [comment]
@jin1027 LottoRecord 자료형의 selected 필드는 List<int> 형이 아닌 List<List<int>>형이 되어야 할것으로 보임(로또번호 하나가 아니라, 여러개를 동시에 만듬). jumjin브랜치의 state.dart -> TicketSet class 참조 ㄱㄱ.

**Comment by rnpfrenfg** [comment]
즐겨찾기 누른 후 확률이 계산되기 전에 즐겨찾기 페이지로 이동하면 오류 나옴.

즐겨찾기 페이지 당첨여부 확인 기능은 티켓이 만들어진 시점에 발표된 번호를 기준으로 함? 아니면 확인하는 시점의 가장 최근 번호를 기준으로 함?

**Comment by jin1027** [comment]
즐겨찾기 페이지 당첨여부 확인 기능은 즐겨찾기 한 주에 발표 난 것을 기준으로 함?

**Comment by song9446** [comment]
가장 가까운 미래에 발표나는걸로 ㄱㄱ

**Comment by jin1027** [comment]
즐겨찾기 페이지 당첨여부 확인 기능은 티켓이 만들어진 시점에 발표된 번호를 기준으로 함? 아니면 확인하는 시점의 가장 최근 번호를 기준으로 함?

**Comment by song9446** [comment]
티켓이 만들어진 시점에서 가장 가까운 미래에 발표된 번호를 기준으로 하는게 맞을듯

**Comment by song9446** [comment]
내가 만든 즐겨찾기 페이지는 예제로 만든건데 당첨확률을 표시해주는데 확률 계산이 아직 안끝나서 coverage5thPrize변수에 null값이 들어있어서 뜨는 것으로 보임 만들때 null값 체크 ㄱㄱ

**Comment by rnpfrenfg** [comment]
당첨확률 계산 끝나면 즐겨찾기페이지 업데이트 바람.. 즐겨찾기 페이지 완성.
이제 당첨 여부 확인 기능 구현해야함.
당첨번호는 서버에서 받아 옴? 아니면 크롤링같은 방법으로 얻음?

**Comment by song9446** [comment]
나도모름 조사한번해보셈

클라이언트에서 크롤링 ㄱㄱ
