### ISSUE TITLE
점진 ToDo

### ISSUE THREAD

**Issue by song9446** [song9446/lottery-optimizer#2]
- [x] 메인UI
- [x] 커버리지 계산 속도 개선
- [x] Shared Preferences 기능 왜 작동안하는지 살펴보기
- [x] 메인UI 로또번호 직접입력 기능
- [x] 커버리지 계산결과 자세히 UI
- [ ] 최적화된 유료버전 / 덜 최적화된 무료버전 분리
